services:
  # Our FastAPI backend web service
  - type: web
    name: self-healing-agent-api
    env: python
    # This tells Render to look for files in the backend directory
    rootDir: backend 
    plan: free # Use the free instance type
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: "/" # Render pings this path to check if the service is healthy
    autoDeploy: true # Automatically deploy on new commits to the main branch
    envVars:
      - key: OPENAI_API_KEY
        fromSecret: true # Link to a secret group
      - key: MONGO_URI
        fromSecret: true
      - key: PYTHON_VERSION
        value: 3.11

# Note: For the database, it's recommended to use a managed service like
# MongoDB Atlas (which we are) or Render's own PostgreSQL/Redis.
# You just need to provide the connection string as a secret.