apiVersion: apps/v1
kind: Deployment
metadata:
  name: project51-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project51
  template:
    metadata:
      labels:
        app: project51
    spec:
      containers:
        - name: project51-container
          # IMPORTANT: Use your Docker Hub username here
          image: shivang139/project51:latest
          # This forces Kubernetes to always check for a new version of the 'latest' image
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 30 # Increased for stability on startup
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
