apiVersion: apps/v1
kind: Deployment
metadata:
  name: project51-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project51
  template:
    metadata:
      labels:
        app: project51
    spec:
      containers:
        - name: project51-container
          image: shivang139/project51:latest # I've put your username here
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          # --- FINAL CHANGE IS HERE ---
          livenessProbe:
            httpGet:
              path: / # Check the main Streamlit page
              port: 8501 # Check the main Streamlit port
            initialDelaySeconds: 45 # Give it more time to start
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: / # Check the main Streamlit page
              port: 8501 # Check the main Streamlit port
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
