apiVersion: v1
kind: Service
metadata:
  name: project51-service
spec:
  type: NodePort
  selector:
    app: project51
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
      nodePort: 30080
