name: CI/CD Pipeline for Self-Healing AI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-validate:
    runs-on: ubuntu-latest
    
    # Set environment variables for the entire job
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        
    - name: Run Tests with Retry
      # Edge Case Handled: CI/CD test flakiness.
      # This uses a third-party action to retry a step.
      # If tests fail once, it will try again up to 2 times.
      uses: nick-invision/retry@v2
      with:
        timeout_seconds: 60
        max_attempts: 2
        command: pytest backend/tests/

    # Optional: This step would trigger the deployment on Render
    # We are using Render's auto-deploy, so this is just for illustration.
    - name: Notify Render of new commit
      if: github.event_name == 'push' && success()
      run: |
        echo "Tests passed. Render will now auto-deploy the latest commit."