name: CI/CD Pipeline

# This workflow runs on any push or pull request to the 'main' branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # This job is named 'test-and-validate'
  test-and-validate:
    runs-on: ubuntu-latest # Use a standard Linux environment

    # Make the secrets you created available to the job
    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      # Step 1: Check out your code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Use the same Python version as your project

      # Step 3: Install all the necessary Python packages
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      # Step 4: Run the tests with retry logic
      # This is a self-healing mechanism for flaky tests.
      - name: Run Pytest with Retry
        # This is a community action that retries a command on failure
        uses: nick-invision/retry@v3
        with:
          # If the command fails, it will wait 10 seconds and try again.
          timeout_seconds: 10
          # It will attempt a maximum of 3 times.
          max_attempts: 3
          # The command to run is your test suite.
          command: pytest backend/tests/

      # This is just a notification step. The actual deployment is handled by Render.
      - name: If tests pass, deployment will be triggered
        if: success()
        run: echo "✅ Tests passed. Render will now auto-deploy."
